### ISSUE TITLE
Unknown command app when compiling

### ISSUE THREAD

**Issue by emanuellima1** [comonicon/Comonicon.jl#159]
I think this is a bug. When I try to compile my project it complains that there isn't a command named "app", but it builds the app anyway. Also, the error doesn't appear when I ask for "app tarball". I am using `incremental=false` and `filter_stdlibs=true` with Comonicon v0.12.1,  PackageCompiler v2.0.3 and Julia v1.7

![image](https://user-images.githubusercontent.com/7927924/145592484-5d184398-ac44-4046-bd3a-c777c9439394.png)

**Comment by Roger-luo** [comment]
do you have the `Comonicon.toml` file available somewhere so that I could try the same configuration. it looks like something wrong with the installation procedure.

**Comment by emanuellima1** [comment]
```TOML
name = "cadCAD"

[install]
completion = false
quiet = false
optimize = 2

[application]
incremental = false
filter_stdlibs = true

[application.precompile]
execution_file = ["deps/precompile.jl"]

[download]
host = "github.com"
user = "cadCAD-org"
repo = "cadCAD.jl"
```
